/*
 * ═══════════════════════════════════════════
 *  Azure Codex – NPC & Player Tracker
 *  SillyTavern Third-Party Extension
 *  ES6 Module v3 – Bug-fixed & Refactored
 * ═══════════════════════════════════════════
 */

import { getContext, extension_settings, renderExtensionTemplateAsync, saveMetadataDebounced } from '../../../extensions.js';
import { SlashCommand } from '../../../slash-commands/SlashCommand.js';
import { ARGUMENT_TYPE, SlashCommandArgument } from '../../../slash-commands/SlashCommandArgument.js';
import { SlashCommandParser } from '../../../slash-commands/SlashCommandParser.js';
import { eventSource, event_types, saveSettingsDebounced } from '../../../../script.js';
import { POPUP_TYPE, callGenericPopup } from '../../../popup.js';

/** @type {any} */
const $ = /** @type {any} */ (window).$;
/** @type {any} */
const jQuery = /** @type {any} */ (window).jQuery;

// ─── Constants ───
const EXT_NAME   = 'third-party/st-azure-codex';
const META_KEY   = 'azure_codex';
const LOG_PREFIX = '[AzureCodex]';

const DEFAULT_SETTINGS = { autoDetect: true, autoDetectStats: true, showFloatBtn: true };

// ─── SAO RPG Config ───
const SAO_STATS = ['STR', 'AGI', 'VIT', 'INT', 'DEX', 'LUK'];
const POINTS_PER_LEVEL = 5;
const BASE_HP = 250;
const BASE_MP = 100;
const HP_PER_VIT = 30;
const MP_PER_INT = 20;
const MIN_APPEARANCES = 2;

// ─── Stat Descriptions & Skill Tree ───
const STAT_INFO = {
    STR: { icon: '⚔', name: 'Strength', desc: 'พลังโจมตีกายภาพ เพิ่มดาเมจธรรมดาและพลังแบก', color: '#ef5350' },
    AGI: { icon: '💨', name: 'Agility', desc: 'ความคล่องตัว เพิ่มความเร็ว, หลบ, คริติคอล', color: '#66bb6a' },
    VIT: { icon: '🛡', name: 'Vitality', desc: 'ความอึด เพิ่ม HP สูงสุด และลดดาเมจ', color: '#42a5f5' },
    INT: { icon: '✨', name: 'Intelligence', desc: 'พลังเวทย์ เพิ่ม MP สูงสุด และดาเมจเวทย์', color: '#ab47bc' },
    DEX: { icon: '🎯', name: 'Dexterity', desc: 'ความแม่นยำ เพิ่มอัตราโจมตีปะทะ, คราฟ', color: '#ffa726' },
    LUK: { icon: '🍀', name: 'Luck', desc: 'โชค เพิ่มดรอปเรท, หาของหายาก, เลี่ยงตาย', color: '#ffd54f' },
};

// Skills are dynamic — generated by the model, not hardcoded
const RANK_COLORS = { F: '#888', E: '#6a8', D: '#5a9', C: '#4a90d9', B: '#ab47bc', A: '#ffd740', S: '#ff4da6', SS: '#ff4da6', SSS: '#ff4da6' };


// ─── Shared Regex Patterns (compiled once) ───
const STAT_EMOJI_PREFIX = '[\s\[\(|•·►▸▹⊳❯»›→⟩☞✦✧✿❖⚔🗡️💎⭐🛡️❤️💙💚💛🔥⚡💧🌟💀👑🎭📊]';
const STAT_NAME_CHARS = 'A-Za-z\u0E00-\u0E7F\u4E00-\u9FFF';
const BOLD_RX_SRC = `\\*\\*([${STAT_NAME_CHARS}][${STAT_NAME_CHARS}\\s]{0,25})\\*\\*`;
const THAI_RX = /[\u0E00-\u0E7F]/;

const KNOWN_STATS = new Set([
    'hp','mp','sp','tp','ep','ap','str','dex','agi','int','wis','con','cha','luk','vit','end',
    'atk','def','matk','mdef','spd','eva','acc','crit','lv','level','exp','gold','money','coin','coins',
    'hunger','thirst','stamina','energy','mana','health','sanity','morale','reputation','karma','luck',
    'attack','defense','magic','speed','power','strength','agility','intelligence','wisdom','charisma',
    'constitution','endurance','dexterity','vitality','armor','damage','shield','resist','resistance',
    'พลังชีวิต','พลังเวทย์','พลังโจมตี','พลังป้องกัน','เลเวล','ค่าโจมตี','ค่าป้องกัน','ความเร็ว',
    'ความหิว','ความกระหาย','พลังงาน','ทอง','เงิน','ชื่อเสียง','สติ','กำลัง','ความคล่องตัว','สติปัญญา',
]);

const STAT_IGNORE_WORDS = new Set([
    'chapter','part','page','line','step','day','year','age','score','round','turn','phase',
    'act','scene','episode','room','floor','no','number','vol','version','ver','pm','am','id','ch','ep','pt',
]);

const COMMON_WORDS = new Set([
    'the','and','but','for','not','you','all','can','had','her','was','one','our','out','are','has','his',
    'how','its','may','new','now','old','see','way','who','did','get','let','say','she','too','use','him',
    'than','then','them','been','have','said','each','will','they','this','that','with','what','your',
    'from','just','very','some','more','also','into','note','action','system','user','info','error','warning','true','false',
]);

const NOT_ITEMS = new Set([
    'hp','mp','sp','exp','xp','gold','money','coin','coins','lv','level',
    'str','agi','vit','int','dex','luk','atk','def','spd','matk','mdef',
    'affection','annoyance','health','mana','stamina','energy',
    'ทอง','เงิน','พลังชีวิต','พลังเวทย์','เลเวล','ความสนิท','ความรำคาญ',
]);

/** Safely show a toastr notification */
const notify = (type, msg, title, opts) => {
    try { globalThis.toastr?.[type]?.(msg, title, opts); } catch { /* noop */ }
};

// ═══════════════════════════════════════════
//  STAT DETECTOR
// ═══════════════════════════════════════════
class StatDetector {
    detect(text) {
        if (!text || text.length < 3) return {};
        const detected = {};
        // FIX: Create fresh regex each call to avoid stale lastIndex
        const rxWithMax = new RegExp(`(?:^|${STAT_EMOJI_PREFIX})\\s*([${STAT_NAME_CHARS}]{1,20}(?:\\s[${STAT_NAME_CHARS}]{1,10})?)\\s*[:：]\\s*([+-]?\\d+(?:\\.\\d+)?)\\s*/\\s*(\\d+(?:\\.\\d+)?)`, 'gm');
        const rxPlain   = new RegExp(`(?:^|${STAT_EMOJI_PREFIX})\\s*([${STAT_NAME_CHARS}]{1,20}(?:\\s[${STAT_NAME_CHARS}]{1,10})?)\\s*[:：]\\s*([+-]?\\d+(?:\\.\\d+)?)\\s*(?=[,\\s\\]\\)|;\\n\\r]|$)`, 'gm');

        for (const m of text.matchAll(rxWithMax)) {
            const name = m[1].trim(), valStr = m[2];
            const value = parseFloat(valStr), max = parseFloat(m[3]);
            const isDelta = valStr.startsWith('+') || valStr.startsWith('-');
            if (this._isValid(name, value)) detected[name] = { value, max, isDelta };
        }
        for (const m of text.matchAll(rxPlain)) {
            const name = m[1].trim(), valStr = m[2];
            const value = parseFloat(valStr);
            const isDelta = valStr.startsWith('+') || valStr.startsWith('-');
            if (!detected[name] && this._isValid(name, value)) detected[name] = { value, max: null, isDelta };
        }
        return detected;
    }

    _isValid(name, value) {
        if (!name || name.length < 2 || name.length > 20) return false;
        const l = name.toLowerCase();
        if (STAT_IGNORE_WORDS.has(l)) return false;
        return KNOWN_STATS.has(l) || Math.abs(value) <= 99999;
    }
}

// ═══════════════════════════════════════════
//  DATA ENGINE
// ═══════════════════════════════════════════
class DataEngine {
    constructor() {
        this.bots = {};
        this.inventory = [];
        this.player = DataEngine.defaultPlayer();
        this._isLoading = false;
        this._backup = null;
    }

    static defaultPlayer() {
        return {
            level: 1, exp: 0, expMax: 100,
            hp: BASE_HP + 5 * HP_PER_VIT, hpMax: BASE_HP + 5 * HP_PER_VIT,
            mp: BASE_MP + 5 * MP_PER_INT, mpMax: BASE_MP + 5 * MP_PER_INT,
            gold: 0, statPoints: 0,
            stats: { STR: 5, AGI: 5, VIT: 5, INT: 5, DEX: 5, LUK: 5 },
            skills: [], // Dynamic: { name, rank, desc, stat? }
        };
    }

    static sanitizeId(id) {
        return String(id).trim().toLowerCase().replace(/\s+/g, '_');
    }

    static calcStage(aff, ann) {
        let s = 0;
        if      (aff >= 90) s = 6;
        else if (aff >= 75) s = 5;
        else if (aff >= 60) s = 4;
        else if (aff >= 40) s = 3;
        else if (aff >= 20) s = 2;
        else if (aff >= 10) s = 1;
        if (ann >= 80 && s > 4) s = 4;
        return s;
    }

    recalcDerived() {
        const p = this.player;
        p.hpMax = BASE_HP + (p.stats.VIT * HP_PER_VIT);
        p.mpMax = BASE_MP + (p.stats.INT * MP_PER_INT);
        p.hp = Math.min(p.hp, p.hpMax);
        p.mp = Math.min(p.mp, p.mpMax);
    }

    levelUp(newLevel) {
        const p = this.player;
        if (newLevel <= p.level) { p.level = newLevel; return 0; }
        const gained = (newLevel - p.level) * POINTS_PER_LEVEL;
        p.statPoints += gained;
        p.level = newLevel;
        p.hp = p.hpMax;
        p.mp = p.mpMax;
        this.recalcDerived();
        return gained;
    }

    allocateStat(name, amt = 1) {
        const p = this.player;
        if (!SAO_STATS.includes(name) || p.statPoints < amt) return false;
        p.stats[name] += amt;
        p.statPoints -= amt;
        this.recalcDerived();
        return true;
    }

    deallocateStat(name, amt = 1) {
        const p = this.player;
        if (!SAO_STATS.includes(name) || p.stats[name] <= 1) return false;
        const actual = Math.min(amt, p.stats[name] - 1);
        p.stats[name] -= actual;
        p.statPoints += actual;
        this.recalcDerived();
        return true;
    }

    // ── NPC ──
    getBotKey(name) {
        if (!name) return null;
        const searchAlias = name.trim().toLowerCase();
        const defaultKey = DataEngine.sanitizeId(name);
        
        // 1. Check if ANY bot has this name exactly or as an alias first (Overrides duplicates)
        for (const [key, bot] of Object.entries(this.bots)) {
            if (key === defaultKey || (bot.name && bot.name.toLowerCase() === searchAlias)) {
                return key;
            }
            if (bot.aliases && bot.aliases.some(a => a.trim().toLowerCase() === searchAlias || DataEngine.sanitizeId(a) === defaultKey)) {
                return key;
            }
        }
        
        // 2. If nothing matches, return the new sanitized key
        return defaultKey;
    }

    addBot(id, name, nickname, dept) {
        const key = DataEngine.sanitizeId(id);
        if (!this.bots[key]) {
            this.bots[key] = { id: key, affection: 0, annoyance: 0, stage: 0, appearances: 0, aliases: [] };
        }
        const bot = this.bots[key];
        bot.name = name || key;
        bot.nickname = nickname || name || key;
        bot.dept = dept || 'Encountered';
        bot.stage = DataEngine.calcStage(bot.affection, bot.annoyance);
        return bot;
    }

    getBot(id) { return this.bots[this.getBotKey(id)] ?? null; }
    removeBot(id) { delete this.bots[this.getBotKey(id)]; }

    updateRelationship(id, affD, annD = 0) {
        const key = this.getBotKey(id);
        const bot = this.bots[key] ?? this.addBot(id, id, id);
        bot.affection = Math.max(0, Math.min(100, bot.affection + affD));
        bot.annoyance = Math.max(0, Math.min(100, bot.annoyance + annD));
        bot.stage = DataEngine.calcStage(bot.affection, bot.annoyance);
        return bot;
    }

    setRelationship(id, aff, ann) {
        const key = this.getBotKey(id);
        const bot = this.bots[key] ?? this.addBot(id, id, id);
        bot.affection = Math.max(0, Math.min(100, aff));
        bot.annoyance = Math.max(0, Math.min(100, ann));
        bot.stage = DataEngine.calcStage(bot.affection, bot.annoyance);
        return bot;
    }

    // ── Inventory ──
    addItem(name, qty = 1) {
        const n = name?.trim();
        if (!n) return;
        const existing = this.inventory.find(i => i.name.toLowerCase() === n.toLowerCase());
        if (existing) existing.qty += qty;
        else this.inventory.push({ name: n, qty });
    }

    removeItem(name, qty = 1) {
        const n = name?.trim();
        if (!n) return false;
        const idx = this.inventory.findIndex(i => i.name.toLowerCase() === n.toLowerCase());
        if (idx === -1) return false;
        this.inventory[idx].qty -= qty;
        if (this.inventory[idx].qty <= 0) this.inventory.splice(idx, 1);
        return true;
    }

    useItem(name) {
        const n = name?.trim();
        if (!n) return null;
        const idx = this.inventory.findIndex(i => i.name.toLowerCase() === n.toLowerCase());
        if (idx === -1) return null;
        const item = this.inventory[idx];
        item.qty -= 1;
        if (item.qty <= 0) this.inventory.splice(idx, 1);
        return item.name;
    }

    // ── Persistence ──
    save() {
        if (this._isLoading) return;
        try {
            const ctx = getContext();
            if (!ctx.chatMetadata) return;
            // FIX: JSON round-trip fallback for safety
            let cloned;
            try {
                cloned = {
                    bots: structuredClone(this.bots),
                    inventory: structuredClone(this.inventory),
                    player: structuredClone(this.player),
                    _backup: structuredClone(this._backup),
                };
            } catch {
                cloned = JSON.parse(JSON.stringify({ bots: this.bots, inventory: this.inventory, player: this.player, _backup: this._backup }));
            }
            ctx.chatMetadata[META_KEY] = cloned;
            saveMetadataDebounced();
        } catch (err) { console.error(LOG_PREFIX, 'Save error:', err); }
    }

    load() {
        this._isLoading = true;
        try {
            const data = getContext().chatMetadata?.[META_KEY];
            const safeClone = (obj) => obj ? JSON.parse(JSON.stringify(obj)) : null;
            this.bots = safeClone(data?.bots) || {};
            for (const bot of Object.values(this.bots)) {
                bot.aliases ??= []; // Migration: add aliases array
            }
            this.inventory = safeClone(data?.inventory) || [];
            this.player = safeClone(data?.player) || DataEngine.defaultPlayer();
            this._backup = safeClone(data?._backup) || null;
            // Migration
            this.player.gold ??= 0;
            this.player.statPoints ??= 0;
            this.player.stats ??= { STR: 5, AGI: 5, VIT: 5, INT: 5, DEX: 5, LUK: 5 };
            this.player.skills ??= []; // Migration: add skills array
            for (const s of SAO_STATS) {
                this.player.stats[s] ??= 5;
            }
            this.recalcDerived();
            console.debug(LOG_PREFIX, `Loaded: ${Object.keys(this.bots).length} NPCs, Lv.${this.player.level}, Gold:${this.player.gold}, Skills:${this.player.skills.length}`);
        } catch (err) {
            console.error(LOG_PREFIX, 'Load error:', err);
            this.bots = {}; this.inventory = []; this.player = DataEngine.defaultPlayer(); this._backup = null;
        } finally { this._isLoading = false; }
    }

    backup() {
        const safeClone = (obj) => obj ? JSON.parse(JSON.stringify(obj)) : null;
        this._backup = {
            bots: safeClone(this.bots),
            inventory: safeClone(this.inventory),
            player: safeClone(this.player)
        };
    }
    
    restore() {
        if (!this._backup) return;
        
        // Preserve user-added aliases, nicknames, and departments across rollbacks
        for (const [k, currentBot] of Object.entries(this.bots)) {
            if (this._backup.bots[k]) {
                const bBot = this._backup.bots[k];
                bBot.aliases = currentBot.aliases ? [...currentBot.aliases] : [];
                bBot.nickname = currentBot.nickname;
                bBot.dept = currentBot.dept;
                bBot.name = currentBot.name;
            }
        }
        
        const safeClone = (obj) => obj ? JSON.parse(JSON.stringify(obj)) : null;
        this.bots = safeClone(this._backup.bots);
        this.inventory = safeClone(this._backup.inventory);
        this.player = safeClone(this._backup.player);
        this.recalcDerived();
    }

    // ── Skills (dynamic) ──
    addSkill(name, rank = '?', desc = '', stat = '') {
        const n = name?.trim();
        if (!n || n.length < 1 || n.length > 60) return false;
        const existing = this.player.skills.find(s => s.name.toLowerCase() === n.toLowerCase());
        if (existing) {
            // Update rank/desc if provided
            if (rank && rank !== '?') existing.rank = rank;
            if (desc) existing.desc = desc;
            if (stat) existing.stat = stat;
            return false; // not new
        }
        this.player.skills.push({ name: n, rank: rank || '?', desc: desc || '', stat: stat || '' });
        return true;
    }

    removeSkill(name) {
        const n = name?.trim()?.toLowerCase();
        if (!n) return false;
        const idx = this.player.skills.findIndex(s => s.name.toLowerCase() === n);
        if (idx === -1) return false;
        this.player.skills.splice(idx, 1);
        return true;
    }

    reset() { this.bots = {}; this.inventory = []; this.player = DataEngine.defaultPlayer(); }
}

// ═══════════════════════════════════════════
//  UI RENDERER
// ═══════════════════════════════════════════
const STAGE_NAMES = ['Stranger','Acquaintance','Noticed','Interest','Tension','Attached','Devoted'];
const STAGE_COLORS = ['#555','#5a7a92','#4a90d9','#6ab8e8','#e8a06a','#e76a6a','#ff4da6'];

class UIRenderer {
    constructor(data, callbacks) {
        this.data = data;
        this.callbacks = callbacks; // { onEditNpc, onRemoveNpc, onUseItem, onDropItem, onReset }
        this.activeTab = 'all';
        this.selectedNpc = null;
    }

    static esc(t) { const d = document.createElement('div'); d.textContent = String(t ?? ''); return d.innerHTML; }
    static escAttr(t) { return String(t ?? '').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/'/g,'&#39;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }

    static getInsight(aff, ann) {
        if (ann >= 90) return 'ระคายเคืองสุดๆ';
        if (ann >= 80) return 'โกรธทุกครั้งที่เจอ';
        if (ann >= 70) return 'อยากเดินหนีทุกที';
        if (ann >= 60) return 'ทนได้ยากมาก';
        if (ann >= 50) return 'เริ่มหลีกเลี่ยง';
        if (aff >= 90) return 'ไม่อยากให้ใครแย่งไป';
        if (aff >= 80) return 'ยอมรับกับตัวเองแล้ว';
        if (aff >= 70) return 'อยากคุยด้วยทุกวัน';
        if (aff >= 60) return 'คิดถึงตอนไม่ได้เจอ';
        if (aff >= 50) return 'จับตามองโดยไม่รู้ตัว';
        if (aff >= 40) return 'ชอบอยู่ใกล้มากขึ้น';
        if (aff >= 30) return 'มีความรู้สึกแปลกๆ';
        if (aff >= 20) return 'รู้สึกว่ามีตัวตน';
        if (aff >= 10) return 'เริ่มจดจำหน้าได้';
        return 'ยังไม่สนใจพิเศษ';
    }

    static renderPips(stage) {
        return Array.from({ length: 7 }, (_, i) =>
            `<div class="ac-pip ${stage === 6 ? 'mx' : (i < stage ? 'f' : '')}" style="background:${i < stage || stage === 6 ? STAGE_COLORS[stage] : ''}"></div>`
        ).join('');
    }

    render() {
        const tabs = document.getElementById('ac-tabs');
        const panels = document.getElementById('ac-panels');
        if (!tabs || !panels) return;
        const npcKeys = Object.keys(this.data.bots).filter(k => {
            const b = this.data.bots[k];
            return (b.appearances || 0) >= MIN_APPEARANCES || b.affection > 0 || b.annoyance > 0;
        });
        this._renderTabs(tabs);
        this._renderPanels(panels, npcKeys);
    }

    _renderTabs(el) {
        const t = (tab) => this.activeTab === tab ? 'active' : '';
        el.innerHTML = `<button class="ac-tab ${t('all')}" data-tab="all">✦ RELATIONSHIP</button>` +
            `<button class="ac-tab ${t('status')}" data-tab="status">⚔ STATUS</button>` +
            `<button class="ac-tab ${t('inventory')}" data-tab="inventory">📦 INVENTORY</button>`;
        el.querySelectorAll('.ac-tab').forEach(btn =>
            btn.addEventListener('click', (e) => { this.activeTab = e.currentTarget.dataset.tab; this.selectedNpc = null; this.render(); })
        );
    }

    _renderPanels(el, npcKeys) {
        const { esc, escAttr, getInsight, renderPips } = UIRenderer;
        let h = '';

        // ── RELATIONSHIP panel ──
        h += `<div class="ac-panel ${this.activeTab === 'all' ? 'active' : ''}">`;
        if (this.selectedNpc && this.data.bots[this.selectedNpc]) {
            const id = this.selectedNpc, b = this.data.bots[id];
            const stageColor = STAGE_COLORS[b.stage] || '#555';
            h += `<button class="ac-back-btn" id="ac-back-to-grid">← BACK</button>
                <div class="ac-detail">
                    <div class="ac-detail-head">
                        <span class="ac-detail-name">${esc(b.name)}</span>
                        <span class="ac-detail-nick">&ldquo;${esc(b.nickname)}&rdquo;</span>
                        <div class="ac-detail-dept">${esc(b.dept)}</div>
                    </div>
                    <div class="ac-stats3">
                        <div class="ac-stat-box"><span class="ac-stat-val" style="color:#e06070">${b.affection}</span><span class="ac-stat-label">AFFECTION</span></div>
                        <div class="ac-stat-box"><span class="ac-stat-val" style="color:#7090d0">${b.annoyance}</span><span class="ac-stat-label">ANNOYANCE</span></div>
                        <div class="ac-stat-box"><span class="ac-stat-val" style="color:${stageColor}">${STAGE_NAMES[b.stage] ?? 'Unknown'}</span><span class="ac-stat-label">STAGE</span></div>
                    </div>
                    <div class="ac-gauge-detail"><span class="ac-gauge-label">❤ AFFECTION</span><div class="ac-gauge-track"><div class="ac-gauge-fill" style="width:${b.affection}%;background:linear-gradient(90deg,#8b1a2d,#e06070,#ff8fa0)"></div></div><span class="ac-gauge-val">${b.affection}/100</span></div>
                    <div class="ac-gauge-detail"><span class="ac-gauge-label">💢 ANNOYANCE</span><div class="ac-gauge-track"><div class="ac-gauge-fill" style="width:${b.annoyance}%;background:linear-gradient(90deg,#1a3a6b,#5080c0,#7090d0)"></div></div><span class="ac-gauge-val">${b.annoyance}/100</span></div>
                    <div class="ac-pips-wrap"><div class="ac-pips-head"><span>ROUTE PROGRESS</span><span style="color:${stageColor}">${STAGE_NAMES[b.stage]} (${b.stage}/6)</span></div><div class="ac-pips">${renderPips(b.stage)}</div></div>
                    <div class="ac-quote">${getInsight(b.affection, b.annoyance)}</div>
                    <div class="ac-detail-actions">
                        <button class="ac-btn ac-btn-edit" data-npc-id="${escAttr(id)}">✎ EDIT</button>
                        <button class="ac-btn ac-btn-remove" data-npc-id="${escAttr(id)}">✕ REMOVE</button>
                    </div>
                </div>`;
        } else if (npcKeys.length === 0) {
            h += `<div class="ac-empty-state"><div class="ac-empty-icon">✦</div><div class="ac-empty-title">NO ENTITIES DETECTED</div><div class="ac-empty-desc">Send messages or use /npc-add to register NPCs</div></div>`;
        } else {
            h += '<div class="ac-grid">';
            for (const id of npcKeys) {
                const b = this.data.bots[id];
                h += `<div class="ac-card" data-target="${escAttr(id)}">
                    <div class="ac-card-name">${esc(b.nickname)}</div>
                    <div class="ac-card-dept">${esc(b.dept)}</div>
                    <div class="ac-card-divider"><span>❧ ${STAGE_NAMES[b.stage]} ❧</span></div>
                    <div class="ac-gauge"><span class="ac-gauge-label">❤ AFF</span><div class="ac-gauge-track"><div class="ac-gauge-fill" style="width:${b.affection}%;background:linear-gradient(90deg,#8b1a2d,#e06070)"></div></div><span class="ac-gauge-val" style="color:#e06070">${b.affection}</span></div>
                    <div class="ac-gauge"><span class="ac-gauge-label">💢 ANN</span><div class="ac-gauge-track"><div class="ac-gauge-fill" style="width:${b.annoyance}%;background:linear-gradient(90deg,#1a3a6b,#5080c0)"></div></div><span class="ac-gauge-val" style="color:#7090d0">${b.annoyance}</span></div>
                </div>`;
            }
            h += '</div>';
        }
        h += '</div>';

        // ── STATUS panel (SAO) ──
        h += `<div class="ac-panel ${this.activeTab === 'status' ? 'active' : ''}">`;
        const p = this.data.player;
        const hpPct = p.hpMax > 0 ? Math.min(100, (p.hp / p.hpMax) * 100) : 0;
        const mpPct = p.mpMax > 0 ? Math.min(100, (p.mp / p.mpMax) * 100) : 0;
        const expPct = p.expMax > 0 ? Math.min(100, (p.exp / p.expMax) * 100) : 0;
        const goldStr = (p.gold ?? 0).toLocaleString();

        h += `<div class="sao-status">
            <div class="sao-level-badge">Lv. ${p.level}</div>
            <div class="sao-bars">
                <div class="sao-bar-row"><span class="sao-bar-label hp-label">HP</span><div class="sao-bar"><div class="sao-bar-fill sao-hp" style="width:${hpPct}%"></div></div><span class="sao-bar-val">${p.hp} / ${p.hpMax}</span></div>
                <div class="sao-bar-row"><span class="sao-bar-label mp-label">MP</span><div class="sao-bar"><div class="sao-bar-fill sao-mp" style="width:${mpPct}%"></div></div><span class="sao-bar-val">${p.mp} / ${p.mpMax}</span></div>
                <div class="sao-bar-row"><span class="sao-bar-label exp-label">EXP</span><div class="sao-bar"><div class="sao-bar-fill sao-exp" style="width:${expPct}%"></div></div><span class="sao-bar-val">${p.exp} / ${p.expMax}</span></div>
            </div>
            <div class="sao-gold-row">💰 <span class="sao-gold-val">${goldStr}</span> Gold</div>
            ${p.statPoints > 0 ? `<div class="sao-points-banner">⚡ UNUSED STAT POINTS: <b>${p.statPoints}</b></div>` : ''}
            <div class="sao-stats-grid">`;
        for (const stat of SAO_STATS) {
            const val = p.stats[stat] ?? 0;
            const canPlus = p.statPoints > 0;
            const canMinus = val > 1;
            const info = STAT_INFO[stat];
            h += `<div class="sao-stat-row">
                <button class="sao-stat-btn sao-stat-minus ${canMinus ? '' : 'disabled'}" data-stat="${stat}" ${canMinus ? '' : 'disabled'}>−</button>
                <span class="sao-stat-name sao-stat-clickable" data-stat="${stat}" style="color:${info.color}" title="Click for details">${info.icon} ${stat}</span>
                <div class="sao-stat-bar"><div class="sao-stat-bar-fill" style="width:${Math.min(100, val)}%;background:linear-gradient(90deg,${info.color}44,${info.color})"></div></div>
                <span class="sao-stat-value">${val}</span>
                <button class="sao-stat-btn sao-stat-plus ${canPlus ? '' : 'disabled'}" data-stat="${stat}" ${canPlus ? '' : 'disabled'}>+</button>
            </div>`;
        }
        h += `</div>`;

        // ── SKILLS section (dynamic — learned from model) ──
        const skills = p.skills || [];
        h += `<div class="sao-skills-header">⚡ SKILLS (${skills.length})</div><div class="sao-skills-list">`;
        if (skills.length === 0) {
            h += `<div class="sao-skills-empty">ยังไม่มีสกิล — สกิลจะถูกเรียนรู้จากเนื้อหาในแชท<br>หรือกด "ขอสกิลใหม่" เพื่อให้ bot คิดสกิลให้</div>`;
        } else {
            for (const skill of skills) {
                const rc = RANK_COLORS[skill.rank?.toUpperCase()] || RANK_COLORS['F'] || '#888';
                const sInfo = skill.stat ? STAT_INFO[skill.stat.toUpperCase()] : null;
                h += `<div class="sao-skill-item sao-skill-clickable" data-skill="${escAttr(skill.name)}" style="cursor:pointer">
                    <span class="sao-skill-rank" style="color:${rc};border-color:${rc}">${esc(skill.rank || '?')}</span>
                    <div class="sao-skill-info">
                        <span class="sao-skill-name">${esc(skill.name)}</span>
                        ${sInfo ? `<span class="sao-skill-from" style="color:${sInfo.color}">${sInfo.icon} ${skill.stat.toUpperCase()}</span>` : ''}
                    </div>
                    <span class="sao-skill-desc">${esc(skill.desc)}</span>
                    <button class="sao-skill-remove" data-skill="${escAttr(skill.name)}" title="ลบสกิล">×</button>
                </div>`;
            }
        }
        h += `</div>`;
        h += `<div class="sao-skill-actions">
            <button class="sao-skill-request-btn" title="ส่งข้อความไปในแชทเพื่อขอสกิลใหม่">✨ ขอสกิลใหม่</button>
            <span class="sao-skill-hint">/skill-add [name] [rank] [desc]</span>
        </div>`;

        h += `</div></div>`;


        // ── INVENTORY panel ──
        h += `<div class="ac-panel ${this.activeTab === 'inventory' ? 'active' : ''}">`;
        if (this.data.inventory.length === 0) {
            h += `<div class="ac-inv-empty">No items in inventory.<br><i style="font-size:.65rem;color:var(--tx3)">Items are auto-detected from bot messages<br>or use /inventory-add [item]</i></div>`;
        } else {
            h += '<div class="ac-inv-list">';
            for (const item of this.data.inventory) {
                h += `<div class="ac-inv-item">
                    <span class="ac-inv-item-name">${esc(item.name)}</span>
                    <span class="ac-inv-item-qty">×${item.qty}</span>
                    <div class="ac-inv-item-actions">
                        <button class="ac-inv-use-btn" data-item="${escAttr(item.name)}" title="Use 1">USE</button>
                        <button class="ac-inv-drop-btn" data-item="${escAttr(item.name)}" title="Drop 1">DROP</button>
                    </div>
                </div>`;
            }
            h += '</div>';
        }
        h += '</div>';

        el.innerHTML = h;
        this._bindEvents(el);
    }

    _bindEvents(el) {
        const cb = this.callbacks;
        el.querySelectorAll('.ac-card').forEach(c =>
            c.addEventListener('click', (e) => { this.selectedNpc = e.currentTarget.dataset.target; this.render(); })
        );
        document.getElementById('ac-back-to-grid')?.addEventListener('click', () => { this.selectedNpc = null; this.render(); });
        // FIX: Use callbacks instead of global controller reference
        el.querySelectorAll('.ac-btn-edit').forEach(b =>
            b.addEventListener('click', (e) => { e.stopPropagation(); cb.onEditNpc?.(e.currentTarget.dataset.npcId); })
        );
        el.querySelectorAll('.ac-btn-remove').forEach(b =>
            b.addEventListener('click', (e) => { e.stopPropagation(); cb.onRemoveNpc?.(e.currentTarget.dataset.npcId); })
        );
        el.querySelectorAll('.ac-inv-use-btn').forEach(b =>
            b.addEventListener('click', (e) => { cb.onUseItem?.(e.currentTarget.dataset.item); })
        );
        el.querySelectorAll('.ac-inv-drop-btn').forEach(b =>
            b.addEventListener('click', (e) => { cb.onDropItem?.(e.currentTarget.dataset.item); })
        );
        // Stat +/- buttons
        el.querySelectorAll('.sao-stat-plus').forEach(b =>
            b.addEventListener('click', (e) => { e.stopPropagation(); cb.onAllocateStat?.(e.currentTarget.dataset.stat); })
        );
        el.querySelectorAll('.sao-stat-minus').forEach(b =>
            b.addEventListener('click', (e) => { e.stopPropagation(); cb.onDeallocateStat?.(e.currentTarget.dataset.stat); })
        );
        // Clickable stat names → show info popup
        el.querySelectorAll('.sao-stat-clickable').forEach(b =>
            b.addEventListener('click', (e) => { e.stopPropagation(); cb.onStatInfo?.(e.currentTarget.dataset.stat); })
        );
        // Clickable skills -> detail popup
        el.querySelectorAll('.sao-skill-clickable').forEach(b =>
            b.addEventListener('click', (e) => {
                if (/** @type {HTMLElement} */(e.target).classList.contains('sao-skill-remove')) return;
                e.stopPropagation();
                cb.onSkillInfo?.(e.currentTarget.dataset.skill);
            })
        );
        // Skill remove buttons
        el.querySelectorAll('.sao-skill-remove').forEach(b =>
            b.addEventListener('click', (e) => { e.stopPropagation(); cb.onRemoveSkill?.(e.currentTarget.dataset.skill); })
        );
        // Request skill button
        el.querySelector('.sao-skill-request-btn')?.addEventListener('click', () => cb.onRequestSkill?.());
    }
}

// ═══════════════════════════════════════════
//  CONTROLLER
// ═══════════════════════════════════════════
class AzureCodexController {
    constructor() {
        this.data = new DataEngine();
        this.detector = new StatDetector();
        this._initialized = false;
        this._eventsRegistered = false; // FIX: guard against double registration
        this.lastProcessedIdx = -1;

        // FIX: UIRenderer uses callbacks, no global reference
        this.ui = new UIRenderer(this.data, {
            onEditNpc: (id) => this.openNpcEditor(id),
            onRemoveNpc: (id) => this.confirmRemoveNpc(id),
            onUseItem: (itemName) => {
                const name = this.data.useItem(itemName);
                if (name) {
                    this.saveAndRender();
                    notify('info', `Used: ${name}`, '✨ Item Used');
                    const textarea = /** @type {HTMLTextAreaElement} */ (document.getElementById('send_textarea'));
                    if (textarea) {
                        textarea.value = `*uses ${name}*`;
                        textarea.dispatchEvent(new Event('input', { bubbles: true }));
                        document.getElementById('send_but')?.click();
                    }
                }
            },
            onDropItem: (itemName) => {
                this.data.removeItem(itemName, 1);
                this.saveAndRender();
                notify('info', `Dropped 1× ${itemName}`, '📦 Item Dropped');
            },
            onAllocateStat: (stat) => {
                const ok = this.data.allocateStat(stat, 1);
                if (ok) {
                    this.saveAndRender();
                    notify('success', `${stat} +1 → ${this.data.player.stats[stat]}  (${this.data.player.statPoints} pts left)`, '⚡ Stat Allocated');
                } else {
                    notify('warning', 'Not enough stat points!', '⚠ Cannot Allocate');
                }
            },
            onDeallocateStat: (stat) => {
                const ok = this.data.deallocateStat(stat, 1);
                if (ok) {
                    this.saveAndRender();
                    notify('info', `${stat} −1 → ${this.data.player.stats[stat]}  (${this.data.player.statPoints} pts left)`, '⚡ Stat Removed');
                } else {
                    notify('warning', `${stat} is already at minimum!`, '⚠ Cannot Remove');
                }
            },
            onStatInfo: (stat) => {
                const info = STAT_INFO[stat];
                const val = this.data.player.stats[stat] ?? 0;
                if (!info) return;
                const learnedSkills = (this.data.player.skills || []).filter(s => s.stat?.toUpperCase() === stat);

                let html = `<div style="font-family:'Cinzel',serif;text-align:center;padding:.5rem 0">
                    <div style="font-size:1.6rem;margin-bottom:.3rem">${info.icon}</div>
                    <div style="font-size:1.1rem;color:${info.color};letter-spacing:.15em;font-weight:700">${stat} — ${info.name}</div>
                    <div style="font-size:.78rem;color:#8aa8c0;margin:.4rem 0 .2rem">${info.desc}</div>
                    <div style="font-size:.85rem;color:${info.color};margin:.4rem 0 .8rem">Current: <b>${val}</b></div>
                    <hr style="border:none;border-top:1px solid #182a3d;margin:.6rem 0">
                    <div style="font-size:.82rem;color:#6ab8e8;letter-spacing:.12em;margin-bottom:.6rem">⚡ LEARNED SKILLS (${stat})</div>`;

                if (learnedSkills.length === 0) {
                    html += `<div style="font-size:.72rem;color:#445;font-style:italic;padding:.5rem 0">ยังไม่มีสกิลที่เรียนรู้สำหรับ ${stat}</div>`;
                } else {
                    for (const skill of learnedSkills) {
                        const rc = RANK_COLORS[skill.rank?.toUpperCase()] || '#888';
                        html += `<div style="display:flex;align-items:center;gap:.6rem;padding:.45rem .5rem;margin:.25rem 0;background:rgba(51,204,255,.06);border:1px solid ${rc}44;border-radius:4px">
                            <span style="font-size:.8rem;font-weight:700;color:${rc};border:1px solid ${rc};width:22px;height:22px;display:flex;align-items:center;justify-content:center;flex-shrink:0">${skill.rank || '?'}</span>
                            <div style="flex:1;text-align:left">
                                <div style="font-size:.8rem;color:#d0e6f0;font-weight:600">${UIRenderer.esc(skill.name)}</div>
                                <div style="font-size:.68rem;color:#8aa8c0">${UIRenderer.esc(skill.desc || 'ไม่มีคำอธิบาย')}</div>
                            </div>
                        </div>`;
                    }
                }

                html += `</div>`;
                callGenericPopup(html, POPUP_TYPE.TEXT);
            },
            onSkillInfo: (name) => {
                const skill = this.data.player.skills.find(s => s.name === name);
                if (!skill) return;
                const rc = RANK_COLORS[skill.rank?.toUpperCase()] || '#8aa8c0';
                const html = `<div style="font-family:'Cinzel',serif;text-align:center;padding:.5rem 0">
                    <div style="font-size:1.6rem;margin-bottom:.3rem;color:${rc}">⚡</div>
                    <div style="font-size:1.1rem;color:${rc};letter-spacing:.15em;font-weight:700">${UIRenderer.esc(skill.name)}</div>
                    <div style="font-size:.85rem;color:#8aa8c0;margin:.2rem 0">[ Rank: ${UIRenderer.esc(skill.rank || '?')} ]</div>
                    <hr style="border:none;border-top:1px solid #182a3d;margin:.6rem 0">
                    <div style="font-size:.9rem;color:#d0e6f0;line-height:1.5;text-align:left;padding:0 .5rem">
                        ${UIRenderer.esc(skill.desc || 'ไม่มีคำอธิบายสกิล')}
                    </div>
                </div>`;
                callGenericPopup(html, POPUP_TYPE.TEXT);
            },
            onRemoveSkill: (name) => {
                const ok = this.data.removeSkill(name);
                if (ok) {
                    this.saveAndRender();
                    notify('info', `ลบสกิล "${name}" แล้ว`, '🗑 Skill Removed');
                }
            },
            onRequestSkill: () => {
                const ta = /** @type {HTMLTextAreaElement} */ (document.getElementById('send_textarea'));
                if (ta) {
                    ta.value = `*เปิดเมนูสกิล ตรวจสอบสกิลใหม่ที่สามารถเรียนรู้ได้ตาม stat และระดับปัจจุบัน*`;
                    ta.dispatchEvent(new Event('input', { bubbles: true }));
                    document.getElementById('send_but')?.click();
                }
            },
        });


    }

    saveAndRender() { this.data.save(); this.ui.render(); }

    // ── NPC Detection ──
    detectNPCsFromMessage(text, isBulk = false) {
        if (!extension_settings[META_KEY]?.autoDetect || !text || this.data._isLoading) return;
        const boldRx = new RegExp(BOLD_RX_SRC, 'g');
        const allNames = [];
        let m;
        
        let playerName = '';
        try { playerName = (getContext().name1 || '').trim().toLowerCase(); } catch(e){}

        while ((m = boldRx.exec(text)) !== null) {
            const name = m[1].trim();
            const lower = name.toLowerCase();
            
            if (lower === playerName) continue;
            if (COMMON_WORDS.has(lower) || KNOWN_STATS.has(lower) || STAT_IGNORE_WORDS.has(lower) || NOT_ITEMS.has(lower)) continue;
            
            if (name.length >= 2) {
                allNames.push(name);
            }
        }
        
        // Removed strictly Thai filter to allow bilingual RPGs (English NPCs with Thai Player)
        const detected = allNames;

        const promoted = [];
        let changed = false;
        // FIX: Dedup names in the same message so appearances don't jump per message
        const uniqueDetected = [...new Set(detected)];
        for (const name of uniqueDetected) {
            const key = this.data.getBotKey(name);
            if (!this.data.bots[key]) {
                this.data.bots[key] = { id: key, name, nickname: name, dept: 'Encountered', affection: 0, annoyance: 0, stage: 0, appearances: 0, aliases: [] };
            }
            this.data.bots[key].appearances = (this.data.bots[key].appearances || 0) + 1;
            changed = true;
            if (this.data.bots[key].appearances === MIN_APPEARANCES) {
                promoted.push(name);
            }
        }
        if (changed && !isBulk) this.saveAndRender();
        if (promoted.length > 0 && !isBulk) {
            notify('info', `Main NPC: ${promoted.join(', ')}`, '✦ NPC Tracked', { timeOut: 4000 });
        }
    }

    cleanupMinorNPCs() {
        const toRemove = [];
        for (const [key, bot] of Object.entries(this.data.bots)) {
            if ((bot.appearances || 0) < MIN_APPEARANCES && bot.affection === 0 && bot.annoyance === 0) {
                toRemove.push(key);
            }
        }
        for (const key of toRemove) delete this.data.bots[key];
        if (toRemove.length > 0) console.debug(LOG_PREFIX, `Cleaned up ${toRemove.length} minor NPCs`);
    }

    // ── Player Stats Detection ──
    detectPlayerStatsFromMessage(text, isBulk = false) {
        if (!extension_settings[META_KEY]?.autoDetectStats || !text || this.data._isLoading) return;
        const detected = this.detector.detect(text);
        const keys = Object.keys(detected);
        if (keys.length === 0) return;

        const p = this.data.player;
        let changed = false;
        const updates = [];

        for (const name of keys) {
            const { value, max, isDelta } = detected[name];
            const upper = name.toUpperCase();

            // Helper to compute final stat from absolute or delta value
            const applyVal = (current, val, maxVal) => {
                const target = isDelta ? current + Math.floor(val) : Math.floor(val);
                return Math.max(0, maxVal ? Math.min(target, maxVal) : target);
            };

            if (['HP', 'พลังชีวิต', 'HEALTH'].includes(upper)) {
                if (max != null && p.hpMax !== max) { p.hpMax = max; changed = true; }
                const v = applyVal(p.hp, value, p.hpMax);
                if (p.hp !== v) { p.hp = v; changed = true; updates.push(`HP: ${v}`); }
            } else if (['MP', 'MANA', 'พลังเวทย์'].includes(upper)) {
                if (max != null && p.mpMax !== max) { p.mpMax = max; changed = true; }
                const v = applyVal(p.mp, value, p.mpMax);
                if (p.mp !== v) { p.mp = v; changed = true; updates.push(`MP: ${v}`); }
            } else if (['EXP', 'XP'].includes(upper)) {
                if (max != null && p.expMax !== max) { p.expMax = max; changed = true; }
                const v = applyVal(p.exp, value, p.expMax);
                if (p.exp !== v) { p.exp = v; changed = true; updates.push(`EXP: ${v}`); }
            } else if (['LV', 'LEVEL', 'เลเวล'].includes(upper)) {
                // levels don't usually use delta, but if they do:
                const newLv = applyVal(p.level, value, null);
                if (newLv > p.level) {
                    const gained = this.data.levelUp(newLv);
                    changed = true;
                    updates.push(`Level Up! Lv.${newLv} (+${gained} pts)`);
                    if (!isBulk) notify('success', `Level ${newLv}! +${gained} stat points!`, '⭐ LEVEL UP!', { timeOut: 5000 });
                } else if (newLv !== p.level && !isDelta) {
                    p.level = newLv; changed = true; updates.push(`Lv.${newLv}`);
                }
            } else if (['GOLD','MONEY','COIN','COINS','ทอง','เงิน'].includes(upper)) {
                const v = applyVal(p.gold, value, null);
                if (p.gold !== v) { p.gold = v; changed = true; updates.push(`Gold: ${v}`); }
            } else if (SAO_STATS.includes(upper)) {
                const v = applyVal(p.stats[upper] || 0, value, null);
                if (p.stats[upper] !== v) { p.stats[upper] = v; changed = true; updates.push(`${upper}: ${v}`); }
            } else if (['ATK','ATTACK','พลังโจมตี','ค่าโจมตี'].includes(upper)) {
                const v = applyVal(p.stats.STR, value, null);
                if (p.stats.STR !== v) { p.stats.STR = v; changed = true; updates.push(`STR: ${v}`); }
            } else if (['DEF','DEFENSE','พลังป้องกัน','ค่าป้องกัน','ARMOR'].includes(upper)) {
                const v = applyVal(p.stats.VIT, value, null);
                if (p.stats.VIT !== v) { p.stats.VIT = v; changed = true; updates.push(`VIT: ${v}`); }
            } else if (['SPD','SPEED','ความเร็ว'].includes(upper)) {
                const v = applyVal(p.stats.AGI, value, null);
                if (p.stats.AGI !== v) { p.stats.AGI = v; changed = true; updates.push(`AGI: ${v}`); }
            } else if (['MAGIC','MATK','สติปัญญา'].includes(upper)) {
                const v = applyVal(p.stats.INT, value, null);
                if (p.stats.INT !== v) { p.stats.INT = v; changed = true; updates.push(`INT: ${v}`); }
            }
        }

        if (changed && !isBulk) {
            this.saveAndRender();
            if (updates.length > 0) notify('info', updates.join(', '), '⚔ Status Updated', { timeOut: 3000 });
        }
    }

    // ── Relationship Detection ──
    detectRelationshipFromMessage(text, isBulk = false) {
        if (!extension_settings[META_KEY]?.autoDetect || !text || this.data._isLoading) return;

        const boldRx = new RegExp(BOLD_RX_SRC, 'g');
        const npcPositions = [];
        let bm;
        while ((bm = boldRx.exec(text)) !== null) {
            const name = bm[1].trim();
            const key = this.data.getBotKey(name);
            if (this.data.bots[key]) {
                npcPositions.push({ key, pos: bm.index });
            }
        }
        // FIX: Early return if no NPCs found (skip expensive regex)
        if (npcPositions.length === 0) return;

        // Support for Delta parsing e.g. "Affection: +5" or "Affection +5"
        const affRx = /(?:affection|ความรัก(?:ใคร่)?|ความสนิท|ความรู้สึก|好感度?|aff|ความชอบ|favorability|love|fondness)\s*[:：]?\s*([+-]?\d+)/gi;
        const annRx = /(?:annoyance|ความรำคาญ|ความโกรธ|ความหงุดหงิด|怒り|ann|irritation|anger|hostility)\s*[:：]?\s*([+-]?\d+)/gi;

        const affValues = [];
        const annValues = [];
        let am;
        while ((am = affRx.exec(text)) !== null) {
            const isDelta = am[1].startsWith('+') || am[1].startsWith('-');
            affValues.push({ pos: am.index, val: parseInt(am[1], 10), isDelta });
        }
        while ((am = annRx.exec(text)) !== null) {
            const isDelta = am[1].startsWith('+') || am[1].startsWith('-');
            annValues.push({ pos: am.index, val: parseInt(am[1], 10), isDelta });
        }

        if (affValues.length === 0 && annValues.length === 0) return;

        const findNearestNpc = (pos) => {
            let best = npcPositions[0];
            for (const npc of npcPositions) {
                if (npc.pos <= pos) best = npc;
                else break;
            }
            return best.key;
        };

        let changed = false;
        const updatedNpcs = new Set();

        for (const { pos, val, isDelta } of affValues) {
            const npcKey = findNearestNpc(pos);
            const bot = this.data.bots[npcKey];
            if (bot) {
                const target = isDelta ? bot.affection + val : val;
                const finalVal = Math.max(0, Math.min(100, target));
                if (bot.affection !== finalVal) {
                    bot.affection = finalVal;
                    bot.stage = DataEngine.calcStage(bot.affection, bot.annoyance);
                    changed = true;
                    updatedNpcs.add(npcKey);
                }
            }
        }
        for (const { pos, val, isDelta } of annValues) {
            const npcKey = findNearestNpc(pos);
            const bot = this.data.bots[npcKey];
            if (bot) {
                const target = isDelta ? bot.annoyance + val : val;
                const finalVal = Math.max(0, Math.min(100, target));
                if (bot.annoyance !== finalVal) {
                    bot.annoyance = finalVal;
                    bot.stage = DataEngine.calcStage(bot.affection, bot.annoyance);
                    changed = true;
                    updatedNpcs.add(npcKey);
                }
            }
        }

        if (changed && !isBulk) {
            this.saveAndRender();
            const summary = [...updatedNpcs].map(k => {
                const b = this.data.bots[k];
                return `${b.nickname}: ❤${b.affection} 💢${b.annoyance}`;
            }).join(' | ');
            notify('info', summary, '✦ Relationship Updated', { timeOut: 4000 });
        }
    }

    // ── Inventory Detection (tighter patterns, dedup) ──
    detectInventoryFromMessage(text, isBulk = false) {
        if (!extension_settings[META_KEY]?.autoDetect || !text || this.data._isLoading) return;

        let changed = false;
        const gains = [];
        const losses = [];
        const seen = new Set(); // FIX: dedup within one message

        const cleanAndAdd = (nameRaw, isLoss) => {
            if (!nameRaw) return;
            let clean = nameRaw.replace(/[*_~`"'「」『』""'']/g, '').trim();
            if (!clean) return;
            
            let qty = 1;
            const qtyMatch = clean.match(/\s*[x×]\s*(\d+)$/i);
            if (qtyMatch) {
                qty = parseInt(qtyMatch[1], 10);
                clean = clean.substring(0, qtyMatch.index).trim();
            }

            if (clean.length < 2 || clean.length > 50) return;
            const lower = clean.toLowerCase();
            if (NOT_ITEMS.has(lower)) return;
            if (/^\d+$/.test(clean) || /^\d+\s*\/\s*\d+$/.test(clean)) return;
            // FIX: Filters for currency strings pretending to be items, e.g. "50 gold", "ทอง 100 เหรียญ"
            if (/^(?:ทอง|เงิน|เหรียญ|gold|money|coins?|exp|xp|hp|mp|sp|lv|level|เลเวล|พลังชีวิต|พลังเวทย์)$/i.test(lower)) return;
            if (/^[\d\s,.]*(?:ทอง|เงิน|เหรียญ|gold|money|coins?|exp|xp)[\d\s,.]*$/i.test(lower)) return;
            // FIX: Skip common verbs/phrases that aren't items
            if (/^(a |the |an |some |any |to |is |it |that |this )/i.test(clean)) return;
            const dedupKey = `${isLoss ? 'L' : 'G'}:${lower}`;
            if (seen.has(dedupKey)) return;
            seen.add(dedupKey);
            if (isLoss) {
                this.data.removeItem(clean, qty);
                losses.push(`${clean}${qty > 1 ? ` x${qty}` : ''}`);
            } else {
                this.data.addItem(clean, qty);
                gains.push(`${clean}${qty > 1 ? ` x${qty}` : ''}`);
            }
            changed = true;
        };

        // FIX: Tighter patterns and rely on regex trim for robust qty
        const gainRx = [
            /(?:ได้รับ(?:ไอเท็ม)?|เก็บได้|พบ|หยิบ|ซื้อ|คว้ามา|รับ)\s*[:：]\s*[「『"']?([^「」『』"'\n]+?)[」』"']?\s*(?:[,、|)\]。]|\n|\r|$)/gim,
            /(?:obtain(?:ed)?|receive[ds]?|got|found|pick(?:ed)?\s*up|bought|loot(?:ed)?|acquire[ds]?|reward(?:ed)?|earned)\s*[:：]\s*[「『"']?([^「」『』"'\n]+?)[」』"']?\s*(?:[,、|)\].]|\n|\r|$)/gim,
            /\[\s*(?:ได้รับ(?:ไอเท็ม)?|item\s*(?:obtained|received|found)?|loot|reward)\s*[:：]?\s*([^\]\n]+?)\s*\]/gim,
        ];

        const lossRx = [
            /(?:เสีย|สูญเสีย|ถูกขโมย|ทิ้ง|ขาย|ใช้)\s*[:：]\s*[「『"']?([^「」『』"'\n]+?)[」』"']?\s*(?:[,、|)\]。]|\n|\r|$)/gim,
            /(?:lost|used|consumed|sold|broke[n]?|destroyed|dropped|spent|discarded)\s*[:：]\s*[「『"']?([^「」『』"'\n]+?)[」』"']?\s*(?:[,、|)\].]|\n|\r|$)/gim,
            /\[\s*(?:เสีย|สูญเสีย|lost|used|consumed)\s*[:：]?\s*([^\]\n]+?)\s*\]/gim,
        ];

        for (const rxTemplate of gainRx) {
            const rx = new RegExp(rxTemplate.source, rxTemplate.flags);
            let m;
            while ((m = rx.exec(text)) !== null) cleanAndAdd(m[1], false);
        }
        for (const rxTemplate of lossRx) {
            const rx = new RegExp(rxTemplate.source, rxTemplate.flags);
            let m;
            while ((m = rx.exec(text)) !== null) cleanAndAdd(m[1], true);
        }

        if (changed && !isBulk) {
            this.saveAndRender();
            if (gains.length > 0) notify('success', `+ ${gains.join(', ')}`, '📦 Item Obtained', { timeOut: 3000 });
            if (losses.length > 0) notify('warning', `- ${losses.join(', ')}`, '📦 Item Lost', { timeOut: 3000 });
        }
    }

    // FIX: Split live vs bulk processing to prevent accumulation bugs
    processMessageLive(text) {
        this.detectNPCsFromMessage(text);
        this.detectPlayerStatsFromMessage(text);
        this.detectRelationshipFromMessage(text);
        this.detectInventoryFromMessage(text);
        this.detectSkillsFromMessage(text);
    }

    processMessageBulk(text) {
        // Bulk scan (chat history): only detect NPCs and skills. Skip stats, inventory, and relationship to prevent history overwriting user edits.
        this.detectNPCsFromMessage(text, true);
        this.detectSkillsFromMessage(text, true);
    }

    // ── Skill Detection ──
    detectSkillsFromMessage(text, isBulk = false) {
        if (!extension_settings[META_KEY]?.autoDetect || !text || this.data._isLoading) return;
        let changed = false;

        // 1. Single-line formats: "Skill Learned: Fireball - Desc"
        const singleLineRx = /(?:Skill\s*(?:Learned|Unlocked|Acquired|Obtained|Gain)|New\s*Skill|เรียนรู้สกิล|ปลดล็อกสกิล|ได้รับสกิล|ได้สกิลใหม่|สกิลใหม่|ความสามารถใหม่)\s*[:：!\-]+\s*\**([^\n*:(]{2,50}?)\**\s*(?:[-:：(]\s*([^\n]{5,150}))?(?:$|\n|\r|\])/gi;
        const rankRx = /(?:Rank|แรงค์|เกรด|ระดับ|Lv|Level)[\s\-:：]*([A-Z]{1,3}|[0-9]+)/i;

        let m;
        while ((m = singleLineRx.exec(text)) !== null) {
            let rawName = m[1].trim().replace(/\*+/g, '');
            rawName = rawName.replace(/[)\]]+$/, '').trim();
            if (rawName.length < 2 || rawName.length > 50) continue;

            let desc = (m[2] || '').trim();
            desc = desc.replace(/^[)\]]+/, '').trim(); // clean leftover bracket
            
            const nearby = text.substring(Math.max(0, m.index - 30), Math.min(text.length, m.index + 100));
            const rm = nearby.match(rankRx);
            const rank = rm ? rm[1].toUpperCase() : '?';

            // Extract rank from desc if present
            const innerRm = desc.match(rankRx);
            let finalRank = rank;
            if (innerRm) {
                finalRank = innerRm[1].toUpperCase();
                desc = desc.replace(innerRm[0], '').replace(/^[\s\-:：()\[\]]+|[\s\-:：()\[\]]+$/g, '');
            }

            const isNew = this.data.addSkill(rawName, finalRank, desc, '');
            if (isNew) {
                changed = true;
                if (!isBulk) notify('success', `เรียนรู้: ${rawName} [${finalRank}]`, '⚡ New Skill!', { timeOut: 4000 });
            } else if (desc) {
                const existing = this.data.player.skills.find(s => s.name.toLowerCase() === rawName.toLowerCase());
                if (existing && (!existing.desc || existing.desc.length < desc.length)) {
                    existing.desc = desc;
                    changed = true;
                }
            }
        }

        // 2. Bullet list format: Match a header like "Skills:" then lines starting with "-"
        const listHeaderRx = /(?:Skills?|Active Skills|Passive Skills|ความสามารถ|สกิล|ทักษะ)\s*[:：]\s*\n((?:[\s*]*[-•*]\s*[^\n]+\n?)+)/gi;
        let mList;
        while ((mList = listHeaderRx.exec(text)) !== null) {
            const listBlock = mList[1];
            const itemRx = /[-•*]\s*\**([^\n*:(]{2,50}?)\**\s*(?:[-:：(]\s*([^\n]{5,150}))?/gi;
            let mItem;
            while ((mItem = itemRx.exec(listBlock)) !== null) {
                let sName = mItem[1].trim().replace(/\*+/g, '');
                let sDesc = (mItem[2] || '').trim();
                sName = sName.replace(/[)\]]+$/, '').trim();
                sDesc = sDesc.replace(/^[)\]]+/, '').trim();
                if (sName.length < 2 || sName.length > 50) continue;
                
                const rm = sDesc.match(rankRx) || sName.match(rankRx);
                const sRank = rm ? rm[1].toUpperCase() : '?';
                if (rm) {
                    sDesc = sDesc.replace(rm[0], '').replace(/^[\s\-:：()\[\]]+|[\s\-:：()\[\]]+$/g, '');
                    sName = sName.replace(rm[0], '').replace(/^[\s\-:：()\[\]]+|[\s\-:：()\[\]]+$/g, '');
                }

                const isNew = this.data.addSkill(sName, sRank, sDesc, '');
                if (isNew) {
                    changed = true;
                    if (!isBulk) notify('success', `จำสกิล: ${sName} [${sRank}]`, '⚡ Skill Synced', { timeOut: 3000 });
                } else if (sDesc) {
                    const existing = this.data.player.skills.find(s => s.name.toLowerCase() === sName.toLowerCase());
                    if (existing && (!existing.desc || existing.desc.length < sDesc.length)) {
                        existing.desc = sDesc;
                        changed = true;
                    }
                }
            }
        }

        if (changed && !isBulk) this.saveAndRender();
    }

    // ── NPC Editor ──
    async openNpcEditor(npcId) {
        const bot = this.data.getBot(npcId);
        if (!bot) return;
        const { esc, escAttr } = UIRenderer;

        const html = `<div class="ac-editor">
            <h3 style="margin:0 0 .8rem;font-family:'Cinzel',serif;letter-spacing:.15em;color:#6ab8e8;text-align:center">✎ EDIT — ${esc(bot.nickname)}</h3>
            <div style="display:grid;grid-template-columns:1fr 1fr;gap:.6rem;margin-bottom:.8rem">
                <div><label style="font-size:.72rem;color:#5a7a92;letter-spacing:.08em;display:block;margin-bottom:.25rem">NICKNAME</label>
                <input id="ac-edit-nickname" type="text" value="${escAttr(bot.nickname)}" style="width:100%;padding:.4rem .5rem;background:#040a14;color:#d0e6f0;border:1px solid #182a3d;font-size:.8rem;box-sizing:border-box"/></div>
                <div><label style="font-size:.72rem;color:#5a7a92;letter-spacing:.08em;display:block;margin-bottom:.25rem">DEPT / ROLE</label>
                <input id="ac-edit-dept" type="text" value="${escAttr(bot.dept)}" style="width:100%;padding:.4rem .5rem;background:#040a14;color:#d0e6f0;border:1px solid #182a3d;font-size:.8rem;box-sizing:border-box"/></div>
            </div>
            <div style="margin-bottom:.8rem">
                <label style="font-size:.72rem;color:#5a7a92;letter-spacing:.08em;display:block;margin-bottom:.25rem">ALIASES (comma separated alternative names)</label>
                <input id="ac-edit-aliases" type="text" value="${escAttr((bot.aliases || []).join(', '))}" placeholder="e.g. Maria, มาเรีย" style="width:100%;padding:.4rem .5rem;background:#040a14;color:#d0e6f0;border:1px solid #182a3d;font-size:.8rem;box-sizing:border-box"/>
            </div>
            <div style="display:grid;grid-template-columns:1fr 1fr;gap:.6rem;margin-bottom:.6rem">
                <div><label style="font-size:.72rem;color:#5a7a92;letter-spacing:.08em;display:block;margin-bottom:.25rem">❤ AFFECTION (0-100)</label>
                <input id="ac-edit-affection" type="range" min="0" max="100" value="${bot.affection}" style="width:100%;accent-color:#e06070"/>
                <div style="text-align:center;font-size:.85rem;color:#e06070" id="ac-edit-aff-val">${bot.affection}</div></div>
                <div><label style="font-size:.72rem;color:#5a7a92;letter-spacing:.08em;display:block;margin-bottom:.25rem">💢 ANNOYANCE (0-100)</label>
                <input id="ac-edit-annoyance" type="range" min="0" max="100" value="${bot.annoyance}" style="width:100%;accent-color:#5080c0"/>
                <div style="text-align:center;font-size:.85rem;color:#7090d0" id="ac-edit-ann-val">${bot.annoyance}</div></div>
            </div>
        </div>`;

        let newAff = bot.affection;
        let newAnn = bot.annoyance;
        let newNick = bot.nickname;
        let newDept = bot.dept;
        let newAlias = (bot.aliases || []).join(', ');

        setTimeout(() => {
            document.getElementById('ac-edit-nickname')?.addEventListener('input', e => newNick = /** @type {HTMLInputElement} */ (e.target).value);
            document.getElementById('ac-edit-dept')?.addEventListener('input', e => newDept = /** @type {HTMLInputElement} */ (e.target).value);
            document.getElementById('ac-edit-aliases')?.addEventListener('input', e => newAlias = /** @type {HTMLInputElement} */ (e.target).value);

            document.getElementById('ac-edit-affection')?.addEventListener('input', e => {
                newAff = parseInt(/** @type {HTMLInputElement} */ (e.target).value) || 0;
                const v = document.getElementById('ac-edit-aff-val'); if (v) v.textContent = String(newAff);
            });
            document.getElementById('ac-edit-annoyance')?.addEventListener('input', e => {
                newAnn = parseInt(/** @type {HTMLInputElement} */ (e.target).value) || 0;
                const v = document.getElementById('ac-edit-ann-val'); if (v) v.textContent = String(newAnn);
            });
        }, 100);

        const ok = await callGenericPopup(html, POPUP_TYPE.CONFIRM);
        if (!ok) return;

        bot.nickname = newNick?.trim() || bot.nickname;
        bot.dept = newDept?.trim() || bot.dept;
        bot.aliases = (newAlias || '').split(',').map(s => s.trim()).filter(Boolean);

        this.data.setRelationship(npcId, newAff, newAnn);
        
        // Preserve manual edits into the backup state to survive Swipes
        if (this.data._backup?.bots?.[npcId]) {
            const bBot = this.data._backup.bots[npcId];
            bBot.nickname = bot.nickname;
            bBot.dept = bot.dept;
            bBot.aliases = [...bot.aliases];
            bBot.affection = bot.affection;
            bBot.annoyance = bot.annoyance;
        }

        this.saveAndRender();
        notify('info', `${bot.nickname} updated`, '✦ NPC Edited');
    }

    async confirmRemoveNpc(npcId) {
        const bot = this.data.getBot(npcId);
        const name = bot ? bot.nickname : npcId;
        const ok = await callGenericPopup(`<h3>Remove NPC</h3><p>Remove <b>${UIRenderer.esc(name)}</b> from tracker?</p>`, POPUP_TYPE.CONFIRM);
        if (ok) { this.ui.selectedNpc = null; this.data.removeBot(npcId); this.saveAndRender(); }
    }

    async confirmReset() {
        const ok = await callGenericPopup(
            '<h3>⟳ Reset Azure Codex?</h3><p>Delete <b>all NPC, stats, and inventory data</b> for this chat?</p><p style="color:#e74c3c;font-size:.85rem">⚠ Cannot be undone.</p>',
            POPUP_TYPE.CONFIRM,
        );
        if (ok) { this.data.reset(); this.ui.activeTab = 'all'; this.saveAndRender(); notify('success', 'All data cleared.', '✦ Reset Complete'); }
    }

    // ── Overlay ──
    createOverlay() {
        document.getElementById('azure-codex-root')?.remove();
        document.getElementById('azure-codex-float-btn')?.remove();
        const btn = document.createElement('button'); btn.id = 'azure-codex-float-btn'; btn.textContent = '✦ Azure Codex'; document.body.appendChild(btn);
        const root = document.createElement('div'); root.id = 'azure-codex-root';
        root.innerHTML = `
        <div class="ac-wrapper">
            <div class="ac-header">
                <div class="ac-header-left"><div class="ac-title">Azure Codex</div><div class="ac-subtitle">NPC & Player Tracker · System Active</div></div>
                <div class="ac-header-right">
                    <div class="ac-heartbeat"><svg width="120" height="20" viewBox="0 0 120 20"><polyline points="0,10 10,10 15,3 20,17 25,10 30,10 35,10 38,5 41,15 44,10 54,10 59,3 64,17 69,10 79,10 84,5 87,15 90,10 100,10 105,3 110,17 115,10 120,10" fill="none" stroke="#003366" stroke-width="1.2"/><polyline points="0,10 10,10 15,3 20,17 25,10 30,10 35,10 38,5 41,15 44,10 54,10 59,3 64,17 69,10 79,10 84,5 87,15 90,10 100,10 105,3 110,17 115,10 120,10" fill="none" stroke="#1e90ff" stroke-width="0.6" opacity="0.5"/></svg></div>
                    <button class="ac-close-btn" id="ac-close-btn">CLOSE</button>
                </div>
            </div>
            <div class="ac-body"><div class="ac-tabs" id="ac-tabs"></div><div id="ac-panels"></div></div>
            <div class="ac-footer">
                <span class="ac-footer-text">Omnia in numeris</span>
                <button class="ac-btn ac-btn-reset" id="ac-reset-btn">⟳ RESET ALL</button>
                <span class="ac-footer-text">✦ Azure Codex · SYSTEM ✦</span>
            </div>
            <div class="ac-bg-deco">❄️</div>
            <span class="ac-ornament tl">✦</span><span class="ac-ornament tr">✦</span><span class="ac-ornament bl">✦</span><span class="ac-ornament br">✦</span>
        </div>`;
        document.body.appendChild(root);
        btn.addEventListener('click', () => root.classList.toggle('show-overlay'));
        document.getElementById('ac-close-btn').addEventListener('click', () => root.classList.remove('show-overlay'));
        document.getElementById('ac-reset-btn').addEventListener('click', () => this.confirmReset());
        this.updateFloatBtn();
        this.ui.render();
    }

    toggleOverlay() { document.getElementById('azure-codex-root')?.classList.toggle('show-overlay'); }
    updateFloatBtn() { const b = document.getElementById('azure-codex-float-btn'); if (b) b.style.display = extension_settings[META_KEY]?.showFloatBtn !== false ? '' : 'none'; }

    // ── Settings ──
    loadSettings() {
        extension_settings[META_KEY] ??= { ...DEFAULT_SETTINGS };
        for (const [k, v] of Object.entries(DEFAULT_SETTINGS)) {
            extension_settings[META_KEY][k] ??= v;
        }
        // FIX: Set checkbox state from saved settings (don't rely on HTML `checked` attr)
        const s = extension_settings[META_KEY];
        $('#azure_codex_auto_detect').prop('checked', s.autoDetect);
        $('#azure_codex_auto_detect_stats').prop('checked', s.autoDetectStats);
        $('#azure_codex_show_float_btn').prop('checked', s.showFloatBtn);
    }

    onSettingsChange() {
        extension_settings[META_KEY].autoDetect = $('#azure_codex_auto_detect').is(':checked');
        extension_settings[META_KEY].autoDetectStats = $('#azure_codex_auto_detect_stats').is(':checked');
        extension_settings[META_KEY].showFloatBtn = $('#azure_codex_show_float_btn').is(':checked');
        saveSettingsDebounced();
        this.updateFloatBtn();
    }

    // ── Slash Commands ──
    registerCommands() {
        const cmd = (name, cb, args, help) => SlashCommandParser.addCommandObject(SlashCommand.fromProps({
            name, callback: cb, helpString: help, returns: 'confirmation message',
            unnamedArgumentList: args ? [SlashCommandArgument.fromProps({ description: args, typeList: [ARGUMENT_TYPE.STRING], isRequired: true })] : [],
        }));

        cmd('codex', async () => { this.toggleOverlay(); return 'Azure Codex toggled.'; }, null, 'Toggle the Azure Codex panel.');
        cmd('npc-add', async (_, v) => { const n = v?.trim(); if (!n) return 'Usage: /npc-add [name]'; this.data.addBot(n,n,n); this.saveAndRender(); return `NPC "${n}" added.`; }, 'NPC name', 'Add NPC.');
        cmd('npc-remove', async (_, v) => { const n = v?.trim(); if (!n) return 'Usage: /npc-remove [name]'; this.data.removeBot(n); this.saveAndRender(); return `NPC "${n}" removed.`; }, 'NPC name', 'Remove NPC.');
        cmd('rel', async (_, v) => {
            const p = v?.trim().split(/\s+/); if (!p || p.length < 2) return 'Usage: /rel [name] [aff] [ann?]';
            this.data.updateRelationship(p[0], parseInt(p[1])||0, parseInt(p[2])||0); this.saveAndRender();
            return `Relationship updated for "${p[0]}".`;
        }, 'name aff [ann]', 'Update NPC relationship.');

        cmd('npc-alias', async (_, v) => {
            const args = v?.trim(); if (!args) return 'Usage: /npc-alias [main_name] [alias_name]';
            const firstSpace = args.indexOf(' ');
            if (firstSpace === -1) return 'Usage: /npc-alias [main_name] [alias_name]';
            const mainName = args.substring(0, firstSpace).trim();
            const aliasName = args.substring(firstSpace + 1).trim();
            
            const mainKey = this.data.getBotKey(mainName);
            let bot = this.data.bots[mainKey];
            if (!bot) {
                bot = this.data.addBot(mainName, mainName, mainName);
            }
            if (!bot.aliases.map(a => a.toLowerCase()).includes(aliasName.toLowerCase())) {
                bot.aliases.push(aliasName);
                this.saveAndRender();
                return `Linked alias "${aliasName}" to main NPC "${bot.nickname}".`;
            }
            return `Alias "${aliasName}" already exists for "${bot.nickname}".`;
        }, 'main_name alias_name', 'Link an alternative name to a main NPC.');

        cmd('inventory-add', async (_, v) => { const n = v?.trim(); if (!n) return 'Usage: /inventory-add [item]'; this.data.addItem(n); this.saveAndRender(); return `Added "${n}".`; }, 'Item name', 'Add item.');
        cmd('inventory-remove', async (_, v) => { const n = v?.trim(); if (!n) return 'Usage: /inventory-remove [item]'; const ok = this.data.removeItem(n); this.saveAndRender(); return ok ? `Removed "${n}".` : `"${n}" not found.`; }, 'Item name', 'Remove item.');
        cmd('use-item', async (_, v) => { const n = v?.trim(); if (!n) return 'Usage: /use-item [name]'; const used = this.data.useItem(n); this.saveAndRender(); return used ? `Used: ${used}` : `"${n}" not found.`; }, 'Item name', 'Use an item from inventory.');
        cmd('gold', async (_, v) => { const amt = parseInt(v?.trim()); if (isNaN(amt)) return 'Usage: /gold [amount]'; this.data.player.gold = Math.max(0, (this.data.player.gold ?? 0) + amt); this.saveAndRender(); return `Gold: ${this.data.player.gold}`; }, 'amount', 'Add or subtract gold. /gold 100 or /gold -50');

        cmd('skill-add', async (_, v) => {
            const args = v?.trim();
            if (!args) return 'Usage: /skill-add [name] [rank] [desc] — e.g. /skill-add Fireball A ยิงลูกไฟ';
            const parts = args.split(/\s+/);
            const name = parts[0];
            const rank = parts[1] || '?';
            const desc = parts.slice(2).join(' ');
            // Check if last word of desc matches a stat name
            let stat = '';
            const lastWord = desc.split(/\s+/).pop()?.toUpperCase();
            if (lastWord && SAO_STATS.includes(lastWord)) {
                stat = lastWord;
            }
            const isNew = this.data.addSkill(name, rank, desc, stat);
            this.saveAndRender();
            return isNew ? `Learned skill: "${name}" [${rank}]` : `Skill "${name}" updated.`;
        }, 'name rank desc', 'Add or update a skill. e.g. /skill-add Fireball A ยิงลูกไฟ');

        cmd('skill-remove', async (_, v) => {
            const n = v?.trim();
            if (!n) return 'Usage: /skill-remove [skill name]';
            const ok = this.data.removeSkill(n);
            this.saveAndRender();
            return ok ? `Removed skill: "${n}"` : `Skill "${n}" not found.`;
        }, 'skill name', 'Remove a learned skill.');


        cmd('stat-alloc', async (_, v) => {
            const p = v?.trim().split(/\s+/); if (!p || p.length < 1) return `Usage: /stat-alloc [${SAO_STATS.join('|')}] [amount?]`;
            const stat = p[0].toUpperCase(), amt = parseInt(p[1])||1;
            if (!SAO_STATS.includes(stat)) return `Invalid stat. Use: ${SAO_STATS.join(', ')}`;
            const ok = this.data.allocateStat(stat, amt); this.saveAndRender();
            return ok ? `Allocated ${amt} pt(s) to ${stat}.` : 'Not enough stat points!';
        }, 'stat [amount]', 'Allocate stat points.');

        cmd('levelup', async (_, v) => {
            const newLv = parseInt(v?.trim()) || (this.data.player.level + 1);
            const gained = this.data.levelUp(newLv); this.saveAndRender();
            return gained > 0 ? `Level Up! Lv.${newLv} (+${gained} stat points)` : `Level set to ${newLv}.`;
        }, '[level]', 'Level up.');

        cmd('codex-reset', async () => { await this.confirmReset(); return 'Done.'; }, null, 'Reset all data.');
        console.debug(LOG_PREFIX, 'Commands registered');
    }

    // ── Events ──
    setupEvents() {
        // FIX: Guard against double registration
        if (this._eventsRegistered) return;
        this._eventsRegistered = true;

        eventSource.on(event_types.CHAT_CHANGED, () => {
            this.data.load(); this.ui.activeTab = 'all'; this.ui.selectedNpc = null; this.ui.render();
            this.lastProcessedIdx = -1;
            setTimeout(() => {
                try {
                    const chat = getContext().chat;
                    if (!Array.isArray(chat)) return;
                    
                    this.lastProcessedIdx = chat.length - 1;

                    // Automatically sync skills from the player's Persona
                    try {
                        const personaStr = String(getContext().chatMetadata?.user_persona || getContext().user_persona || '');
                        if (personaStr) this.detectSkillsFromMessage(personaStr, true);
                    } catch(e) {}

                    // BUG FIX: Zero out appearances before recounting to prevent unbounded accumulation
                    for (const bot of Object.values(this.data.bots)) {
                        bot.appearances = 0;
                    }

                    // FIX: Use bulk processing (NPC + stats only, no inventory/relationship)
                    for (const msg of chat) {
                        if (!msg.is_user && !msg.is_system && msg.mes) this.processMessageBulk(msg.mes);
                    }
                    this.cleanupMinorNPCs();
                    this.saveAndRender();
                } catch (err) { console.warn(LOG_PREFIX, 'Scan error:', err); }
            }, 500);
        });

        eventSource.on(event_types.CHARACTER_MESSAGE_RENDERED, (idx) => {
            try {
                const msg = getContext().chat?.[idx];
                if (!msg || msg.is_user || msg.is_system) return;

                if (idx === this.lastProcessedIdx) {
                    this.data.restore();
                } else if (idx > this.lastProcessedIdx) {
                    this.data.backup();
                } else {
                    return; // Ignore older messages to prevent double-applying
                }

                // Live messages get full processing
                this.processMessageLive(msg.mes);
                this.lastProcessedIdx = idx;
            } catch (err) { console.warn(LOG_PREFIX, 'Message error:', err); }
        });

        eventSource.on(event_types.MESSAGE_DELETED, (idx) => {
            if (idx === this.lastProcessedIdx) {
                this.data.restore();
                this.lastProcessedIdx = idx - 1;
                this.saveAndRender();
            }
        });
    }

    // ── Init ──
    async init() {
        try {
            const settingsHtml = await renderExtensionTemplateAsync(EXT_NAME, 'settings');
            $('#extensions_settings2').append(settingsHtml);
        } catch {
            $('#extensions_settings2').append(`
            <div id="azure-codex-settings"><div class="inline-drawer">
                <div class="inline-drawer-toggle inline-drawer-header"><b>Azure Codex – NPC & Player Tracker</b><div class="inline-drawer-icon fa-solid fa-circle-chevron-down down"></div></div>
                <div class="inline-drawer-content"><div class="flex-container flexFlowColumn">
                    <label class="checkbox_label" for="azure_codex_auto_detect"><input id="azure_codex_auto_detect" type="checkbox"/><span>Auto-detect NPCs</span></label>
                    <label class="checkbox_label" for="azure_codex_auto_detect_stats"><input id="azure_codex_auto_detect_stats" type="checkbox"/><span>Auto-detect player stats</span></label>
                    <label class="checkbox_label" for="azure_codex_show_float_btn"><input id="azure_codex_show_float_btn" type="checkbox"/><span>Show floating button</span></label>
                    <hr/><div class="flex-container"><button id="azure_codex_open_panel" class="menu_button"><i class="fa-solid fa-compass"></i><span>Open Azure Codex</span></button></div>
                </div></div>
            </div></div>`);
        }

        this.loadSettings();
        $('#azure_codex_auto_detect, #azure_codex_auto_detect_stats, #azure_codex_show_float_btn').on('change', () => this.onSettingsChange());
        $('#azure_codex_open_panel').on('click', () => this.toggleOverlay());
        $('#extensionsMenu').append(`<div id="azure_codex_wand_btn" class="list-group-item flex-container flexGap5"><div class="fa-solid fa-compass extensionsMenuExtensionButton"></div>Azure Codex</div>`);
        $('#azure_codex_wand_btn').on('click', () => this.toggleOverlay());

        this.createOverlay();
        this.registerCommands();
        this.setupEvents();
        try { if (getContext().chatMetadata) { this.data.load(); this.ui.render(); } } catch { /* noop */ }
        this._initialized = true;
        console.log(LOG_PREFIX, 'Azure Codex loaded ✦');
    }
}

// ═══════════════════════════════════════════
const controller = new AzureCodexController();
jQuery(() => controller.init());
